### PR TITLE
added custom-scrollbar

### PR DESCRIPTION
**Pull request by mwenku**
## added custom scrollbar
I added a custom scroll bar using css here is a screenshot 

{236D7C6C-9FBC-4B2E-9787-0BA4369F81CF} png

### CODE REVIEW

**Comment by Martin1998215** [comment]
thank you so much. i will do that.

**Comment by Martin1998215** [comment]
Do you mind if i can know more about you ?
I like interacting with programmers

**Comment by mwenku** [comment]
Yes sure. Here is my facebook https://web.facebook.com/mwelwa.jsx

I'm Mwelwa Nkuta currently living in mbala. We'll talk more on facebook

**Comment by Martin1998215** [comment]
Dont you use twitter or whatsApp?

Am barely a Facebook user

**Comment by mwenku** [comment]
My Twitter  twitter.com/Merlee4t
WhatsApp 0964487617

**Comment by mwenku** [comment]
Here is my WhatsApp 0964487617

**Comment by Martin1998215** [comment]
Sure thing.

let me follow you and keep in touch with you

**Pull request closed without merging**
